"""Six synthetic SurakshaSetu journeys; no browser, DB, or LLM calls."""

from .builders import Journey, cohort

CONSENT = '[2] checkbox "Auto-renew and share my data with partners" checked'


def demo_cohort():
    impatient = Journey("impatient-01")
    impatient.step("index.html", to="plans.html").step("plans.html", to="details.html")
    impatient.step("details.html", to="verify.html")
    impatient.step("verify.html", label="Send OTP", page_hash="otp-hidden")
    impatient.step("verify.html", "wait", page_hash="otp-hidden")
    impatient.step("verify.html", label="Send OTP", page_hash="otp-hidden", screenshot=True)
    impatient.finish("abandoned")

    low = Journey("low_literacy-01")
    low.step("index.html", label="Get Started", to="learn.html")
    low.step("learn.html", "scroll", elements=0, prompt="Insurance article")
    low.step("learn.html", "back", elements=0, prompt="Insurance article", to="index.html", screenshot=True)
    low.step("index.html", label="Get a Quote", to="plans.html")
    low.step("plans.html", to="details.html")
    low.step("details.html", "type", text="tomorrow", label="Date of birth", changed=True)
    low.step("details.html", changed=True)
    low.step("details.html", alerts=["Invalid input"], screenshot=True)
    low.finish("failed")

    power = Journey("power-01")
    power.step("index.html", label="Get a Quote", to="plans.html")
    power.step("plans.html", to="details.html")
    power.step("details.html", "type", text="Test Applicant", changed=True)
    power.step("details.html", "type", text="9876543210", changed=True)
    power.step("details.html", "type", text="01/01/1990", changed=True)
    power.step("details.html", to="verify.html")
    power.step("verify.html", label="Send OTP")
    power.step("verify.html", "wait", changed=True)
    power.step("verify.html", "type", text="123456", changed=True)
    power.step("verify.html", to="review.html")
    power.step("review.html", to="pay.html")
    power.step("pay.html", label="Proceed", prompt="Total ₹4,812\n" + CONSENT, to="confirmed.html", screenshot=True)
    power.finish()

    cautious = Journey("cautious-01")
    cautious.step("index.html", to="plans.html").step("plans.html", to="details.html")
    cautious.step("details.html", to="verify.html").step("verify.html", to="review.html")
    cautious.step("review.html", to="pay.html", signals=["risk_page"], delta=0.15)
    cautious.step("pay.html", "give_up", prompt="Total ₹4,812 + applicable charges*\n" + CONSENT, screenshot=True)
    cautious.finish("abandoned")

    explorer = Journey("explorer-01")
    explorer.step("index.html", label="Explore Plans", to="explore.html")
    explorer.step("explore.html", label="Talk to an advisor", changed=True)
    explorer.step("explore.html", label="Talk to an advisor", alerts=["All advisors are busy"])
    explorer.step("explore.html", "back", to="index.html", screenshot=True)
    explorer.step("index.html", to="plans.html").step("plans.html", "scroll")
    explorer.finish("budget_exhausted")

    chaos = Journey("chaos-01")
    chaos.step("index.html", to="explore.html")
    chaos.step("explore.html", "back", to="index.html")
    chaos.step("index.html", to="plans.html")
    chaos.step("plans.html", "scroll").step("plans.html", to="details.html")
    chaos.step("details.html", "type", label="Name", text="Test Applicant", changed=True)
    chaos.step("details.html", "type", label="Mobile", text="12345", tags=["edge_case_input"], changed=True)
    chaos.step("details.html", "type", label="Date of birth", text="01/01/1990", changed=True)
    chaos.step("details.html", to="verify.html", screenshot=True)
    chaos.step("verify.html", label="Send OTP")
    chaos.step("verify.html", label="Send OTP")
    chaos.step("verify.html", "wait", changed=True)
    chaos.step("verify.html", "type", text="123456", changed=True)
    chaos.step("verify.html", to="review.html")
    chaos.step("review.html", "scroll").step("review.html", to="pay.html")
    chaos.step("pay.html", label="Proceed", tags=["double_click"], prompt="Total ₹4,812\n" + CONSENT, changed=True)
    chaos.step("pay.html", "wait", prompt="Total ₹4,812\nPayment 1 ₹4,812\nPayment 2 ₹4,812", screenshot=True)
    chaos.step("pay.html", "wait", to="confirmed.html")
    chaos.finish()
    return cohort(impatient, low, power, cautious, explorer, chaos)
